### ISSUE TITLE
missing bib files in index.Rmd

### ISSUE THREAD

**Issue by wenjie2wang** [jun-yan/stat-5361#1]
Hi Professor,

I was trying to render the notes and I found that two bib files `stco.bib` and `packages.bib` specified in the `index.Rmd` are missing in the master branch now.  Thanks.

**Comment by jun-yan** [comment]
I just added stco.bib. The package.bib file was generated.

**Comment by wenjie2wang** [comment]
Thanks!  It works for me now.

Closed this issue.
